// Todo texto de UI vive aqui. Interface em português, sem i18n na Fase 1, mas com as strings
// já extraídas para não pagar refatoração depois (memory/decisions.md).
export const mensagens = {
  app: {
    nome: 'KORA FORGE',
    navegacao: 'Navegação principal',
    semProjetoAtivo: 'Nenhum projeto ativo',
    versaoDesconhecida: '…',
  },
  menu: {
    projetos: 'Projetos',
    eficiencia: 'Eficiência',
    config: 'Configurações',
  },
  estados: {
    carregando: 'Carregando…',
    erroGenerico: 'Não deu para falar com a API local.',
    tentarDeNovo: 'Tentar de novo',
  },
  semSessao: {
    titulo: 'Abra o Forge pelo link do terminal',
    texto: 'O link impresso pelo comando abaixo carrega o token de sessão. Sem ele, o browser não consegue falar com a API local, de propósito.',
    comando: 'npm run forge',
    comandoRotulo: 'comando para subir o Forge',
  },
  registry: {
    titulo: 'Projetos',
    novo: 'Novo projeto',
    busca: { rotulo: 'Buscar', micro: 'Filtra por nome ou slug.', placeholder: 'nome ou slug' },
    filtro: {
      rotulo: 'Status',
      micro: 'Arquivados só aparecem escolhendo o filtro.',
      ativos: 'Ativos',
      rascunho: 'Rascunho',
      pronto_para_materializar: 'Pronto para materializar',
      materializado: 'Materializado',
      arquivado: 'Arquivados',
    },
    vazio: {
      titulo: 'Nenhum projeto ainda',
      texto: 'Escolha um menu para começar. O wizard preenche o blueprint e a materialização cria a pasta.',
    },
    semResultado: {
      titulo: 'Nenhum projeto com esse filtro',
      texto: 'Tente outro nome ou outro status.',
      limpar: 'Limpar filtros',
    },
    avisoWorkspace: 'Nenhum workspace configurado. Dá para criar projetos, mas materializar exige a pasta raiz.',
    configurar: 'Configurar workspace',
    ultimaAlteracao: 'Alterado em',
    etapa: 'Etapa',
    semCaminho: 'ainda não materializado',
  },
  preset: {
    etapasSufixo: 'etapas',
    categoria: { site: 'Site', aplicacao: 'Aplicação', api: 'API', automacao: 'Automação' },
  },
  novoProjeto: {
    titulo: 'Novo projeto',
    escolha: 'Escolha o menu',
    escolhido: 'Menu escolhido',
    trocar: 'Trocar menu',
    nome: {
      rotulo: 'Nome do projeto',
      micro: 'Vira o nome da pasta e o slug do repositório.',
      slug: 'Slug',
      slugVazio: 'digite um nome com letra ou número',
      placeholder: 'Meu app',
    },
    criar: 'Criar projeto',
    voltar: 'Voltar para projetos',
  },
  projeto: {
    naoEncontrado: 'Projeto não encontrado.',
    voltar: 'Voltar para projetos',
    preset: 'Menu',
    etapaAtual: 'Próxima etapa',
    caminho: 'Pasta',
    semCaminho: 'ainda não materializado',
    renomear: 'Renomear',
    salvarNome: 'Salvar nome',
    cancelar: 'Cancelar',
    nome: { rotulo: 'Nome', micro: 'O slug não muda ao renomear.' },
    arquivar: 'Arquivar',
    restaurar: 'Restaurar',
    arquivado: 'Projeto arquivado. Restaure para continuar.',
    wizardIndisponivel: 'O wizard ainda não está disponível. O blueprint fica na etapa inicial até lá.',
    versoes: 'Versões do blueprint',
    versaoAtiva: 'ativa',
    blueprintVersao: 'Blueprint',
  },
  etapas: {
    identidade: 'Identidade',
    escopo: 'Escopo e público',
    arquitetura: 'Arquitetura e stack',
    design: 'Design',
    dados: 'Dados e entidades',
    apis: 'APIs e integrações',
    seguranca: 'Segurança e custo',
    fundacao: 'Fundação',
    materializar: 'Materializar',
  },
  config: {
    titulo: 'Configurações',
    salvar: 'Salvar',
    salvo: 'Configurações salvas.',
    workspace: {
      rotulo: 'Workspace',
      micro: 'Pasta raiz onde os projetos são criados. Nada é escrito fora dela.',
      placeholder: 'D:\\dev\\kora',
    },
    tema: {
      rotulo: 'Tema',
      micro: 'Aparência da ferramenta. O tema claro chega na Fase 5.',
      escuro: 'Escuro',
      claro: 'Claro',
    },
    teto: {
      rotulo: 'Teto mensal do copiloto (USD)',
      micro: 'Quando o consumo bate o teto, o copiloto desliga sozinho.',
      invalido: 'Informe um número maior ou igual a zero.',
    },
  },
  campo: {
    padrao: 'Padrão',
  },
  selecao: {
    padraoKora: 'padrão Kora',
  },
  selo: {
    rascunho: 'rascunho',
    pronto: 'pronto',
    materializado: 'materializado',
    arquivado: 'arquivado',
    ativa: 'ativa',
    invalida: 'inválida',
    economico: 'econômico',
    equilibrio: 'equilíbrio',
    frontier: 'frontier',
    amostra_pequena: 'amostra pequena',
    recomendado: 'recomendado',
  },
  eficiencia: {
    titulo: 'Eficiência',
    subtitulo: 'Qual modelo entrega mais por dólar, e o que usar em cada etapa do copiloto.',
    catalogo: 'Preços do catálogo v{versao}, atualizado em {data}. Fonte: {fonte}.',
    filtros: {
      intencao: {
        rotulo: 'Intenção da aplicação',
        micro: 'Muda a recomendação por etapa e filtra o ranking. Vem do preset quando há projeto.',
        todas: 'Todas as intenções',
      },
      periodo: {
        rotulo: 'Período',
        micro: 'Janela do gasto e do ranking.',
        mes: 'Mês atual',
        '30d': 'Últimos 30 dias',
        tudo: 'Desde o início',
      },
    },
    intencoes: {
      site: 'Site',
      aplicacao: 'Aplicação web',
      local: 'Aplicação local',
      api: 'API ou serviço',
      automacao: 'Automação ou bot',
    },
    etapas: {
      'identidade-redigir': 'Redigir identidade',
      'personas-derivar': 'Derivar personas',
      'nome-sugerir': 'Sugerir nomes',
      'entidades-derivar': 'Derivar entidades',
      'regras-redigir': 'Redigir regras de negócio',
      'blueprint-revisar': 'Revisar blueprint',
    },
    indicadores: {
      gasto: 'Gasto no período',
      doTeto: 'do teto de',
      semTeto: 'teto zerado nas configurações',
      chamadas: 'Chamadas',
      sucessos: 'com sucesso',
      taxaSucesso: 'Taxa de sucesso',
      melhorModelo: 'Mais eficiente',
      semDado: 'sem dado ainda',
    },
    vazio: {
      titulo: 'Nenhuma chamada registrada neste período',
      texto: 'O copiloto nasce desligado, então não há gasto. O ranking aparece quando houver chamadas. A recomendação por etapa e o simulador abaixo já funcionam sem dado.',
    },
    ranking: {
      titulo: 'Ranking por eficiência',
      micro: 'Pontuação é sucessos por dólar, relativa ao melhor modelo (100). Chamada que falhou custa, mas não conta como sucesso.',
      grafico: 'Pontuação por modelo',
      colunas: {
        modelo: 'Modelo',
        pontuacao: 'Pontuação',
        chamadas: 'Chamadas',
        taxaSucesso: 'Sucesso',
        custoMedio: 'Custo médio',
        custoPorSucesso: 'Custo por sucesso',
        latencia: 'Latência média',
      },
      semSucesso: 'nenhum',
      semLatencia: 'sem medição',
    },
    porEtapa: {
      titulo: 'Gasto por etapa',
      colunas: { etapa: 'Etapa', chamadas: 'Chamadas', sucessos: 'Sucessos', custo: 'Custo', modelo: 'Modelo mais usado' },
    },
    recomendacao: {
      titulo: 'Recomendação por etapa',
      micro: 'Padrão Kora para {intencao}. O modelo de escalada só entra se a saída falhar na validação de schema.',
      modelo: 'Modelo',
      escalar: 'Escala para',
      esforco: 'Esforço',
      semEsforco: 'não se aplica',
      maxTokens: 'Saída máxima',
      cache: 'Cache',
      custoTipico: 'Chamada típica',
      comCache: 'com cache',
      escalada: 'na escalada',
      tokens: 'tokens',
    },
    simulador: {
      titulo: 'Simulador de custo mensal',
      micro: 'Calculado com o catálogo versionado, sem chamar a API. Com cache ligado, assume 60% do prefixo lido do cache.',
      entrada: { rotulo: 'Tokens de entrada por chamada', micro: 'Prompt de sistema, preset e contexto enviados a cada chamada.' },
      saida: { rotulo: 'Tokens de saída por chamada', micro: 'Tamanho médio da resposta em JSON.' },
      chamadas: { rotulo: 'Chamadas por mês', micro: 'Um projeto completo no wizard gasta cerca de seis chamadas.' },
      cache: { rotulo: 'Cache de prompt', micro: 'Reaproveita o prefixo estável entre chamadas. Sempre ligado no copiloto.' },
      lote: { rotulo: 'Batch API', micro: 'Metade do preço quando ninguém espera a resposta. O wizard espera, então fica desligado.' },
      ligado: 'Ligado',
      desligado: 'Desligado',
      colunas: { modelo: 'Modelo', porChamada: 'Por chamada', porMes: 'Por mês', doTeto: 'Do teto' },
      invalido: 'Informe um número maior ou igual a zero. Usando zero.',
      semTeto: 'sem teto',
    },
  },
  chave: {
    copiar: 'Copiar',
    copiado: 'Copiado',
  },
};
