// Todo texto de UI vive aqui. Interface em português, sem i18n na Fase 1, mas com as strings
// já extraídas para não pagar refatoração depois (memory/decisions.md).
export const mensagens = {
  app: {
    nome: 'KORA FORGE',
    navegacao: 'Navegação principal',
    semProjetoAtivo: 'Nenhum projeto ativo',
    versaoDesconhecida: '…',
  },
  menu: {
    projetos: 'Projetos',
    config: 'Configurações',
  },
  estados: {
    carregando: 'Carregando…',
    erroGenerico: 'Não deu para falar com a API local.',
    tentarDeNovo: 'Tentar de novo',
  },
  semSessao: {
    titulo: 'Abra o Forge pelo link do terminal',
    texto: 'O link impresso pelo comando abaixo carrega o token de sessão. Sem ele, o browser não consegue falar com a API local, de propósito.',
    comando: 'npm run forge',
    comandoRotulo: 'comando para subir o Forge',
  },
  registry: {
    titulo: 'Projetos',
    novo: 'Novo projeto',
    busca: { rotulo: 'Buscar', micro: 'Filtra por nome ou slug.', placeholder: 'nome ou slug' },
    filtro: {
      rotulo: 'Status',
      micro: 'Arquivados só aparecem escolhendo o filtro.',
      ativos: 'Ativos',
      rascunho: 'Rascunho',
      pronto_para_materializar: 'Pronto para materializar',
      materializado: 'Materializado',
      arquivado: 'Arquivados',
    },
    vazio: {
      titulo: 'Nenhum projeto ainda',
      texto: 'Escolha um menu para começar. O wizard preenche o blueprint e a materialização cria a pasta.',
    },
    semResultado: {
      titulo: 'Nenhum projeto com esse filtro',
      texto: 'Tente outro nome ou outro status.',
      limpar: 'Limpar filtros',
    },
    avisoWorkspace: 'Nenhum workspace configurado. Dá para criar projetos, mas materializar exige a pasta raiz.',
    configurar: 'Configurar workspace',
    ultimaAlteracao: 'Alterado em',
    etapa: 'Etapa',
    semCaminho: 'ainda não materializado',
  },
  preset: {
    etapasSufixo: 'etapas',
    categoria: { site: 'Site', aplicacao: 'Aplicação', api: 'API', automacao: 'Automação' },
  },
  novoProjeto: {
    titulo: 'Novo projeto',
    escolha: 'Escolha o menu',
    escolhido: 'Menu escolhido',
    trocar: 'Trocar menu',
    nome: {
      rotulo: 'Nome do projeto',
      micro: 'Vira o nome da pasta e o slug do repositório.',
      slug: 'Slug',
      slugVazio: 'digite um nome com letra ou número',
      placeholder: 'Meu app',
    },
    criar: 'Criar projeto',
    voltar: 'Voltar para projetos',
  },
  projeto: {
    naoEncontrado: 'Projeto não encontrado.',
    voltar: 'Voltar para projetos',
    preset: 'Menu',
    etapaAtual: 'Próxima etapa',
    caminho: 'Pasta',
    semCaminho: 'ainda não materializado',
    renomear: 'Renomear',
    salvarNome: 'Salvar nome',
    cancelar: 'Cancelar',
    nome: { rotulo: 'Nome', micro: 'O slug não muda ao renomear.' },
    arquivar: 'Arquivar',
    restaurar: 'Restaurar',
    arquivado: 'Projeto arquivado. Restaure para continuar.',
    comecar: 'Começar o wizard',
    continuar: 'Continuar de onde parou',
    progresso: (feitas, total) => `${feitas} de ${total} etapas`,
    versoes: 'Versões do blueprint',
    versaoAtiva: 'ativa',
    blueprintVersao: 'Blueprint',
  },
  etapas: {
    identidade: 'Identidade',
    escopo: 'Escopo e público',
    arquitetura: 'Arquitetura e stack',
    design: 'Design',
    dados: 'Dados e entidades',
    apis: 'APIs e integrações',
    seguranca: 'Segurança e custo',
    fundacao: 'Fundação',
    materializar: 'Materializar',
  },
  config: {
    titulo: 'Configurações',
    salvar: 'Salvar',
    salvo: 'Configurações salvas.',
    workspace: {
      rotulo: 'Workspace',
      micro: 'Pasta raiz onde os projetos são criados. Nada é escrito fora dela.',
      placeholder: 'D:\\dev\\kora',
    },
    tema: {
      rotulo: 'Tema',
      micro: 'Aparência da ferramenta. O tema claro chega na Fase 5.',
      escuro: 'Escuro',
      claro: 'Claro',
    },
    teto: {
      rotulo: 'Teto mensal do copiloto (USD)',
      micro: 'Quando o consumo bate o teto, o copiloto desliga sozinho.',
      invalido: 'Informe um número maior ou igual a zero.',
    },
  },
  campo: {
    padrao: 'Padrão',
  },
  selecao: {
    padraoKora: 'padrão Kora',
  },
  selo: {
    rascunho: 'rascunho',
    pronto: 'pronto',
    materializado: 'materializado',
    arquivado: 'arquivado',
    ativa: 'ativa',
    invalida: 'inválida',
  },
  chave: {
    copiar: 'Copiar',
    copiado: 'Copiado',
  },
  plano: {
    titulo: 'Plano de materialização',
    resumo: (arquivos, bytes, comandos) => `${arquivos} arquivos, ${bytes}, e ${comandos} comandos depois da escrita.`,
    raiz: 'pasta do projeto',
    nadaEscrito: 'Este é o plano. Nada foi escrito em disco ainda.',
    arquivos: 'Arquivos',
    raizDoProjeto: 'raiz do projeto',
    comandos: 'Comandos',
    obrigatorio: 'obrigatório',
    opcional: 'opcional',
    longaDuracao: 'longa duração',
    conflitos: (n) => (n === 1 ? '1 arquivo já existe' : `${n} arquivos já existem`),
    conflitoExplicacao: 'Estes arquivos existem no disco com conteúdo diferente. Nada é sobrescrito sem sua decisão.',
    pendencias: (n) => (n === 1 ? '1 pendência' : `${n} pendências`),
    substitui: (tamanho) => `(hoje ${tamanho})`,
    acao: { criar: 'novo', sobrescrever: 'conflito', pular: 'igual' },
    carregando: 'Montando o plano…',
    erroWorkspace: 'Configurar workspace',
  },
  materializacao: {
    aprovar: 'Aprovar e materializar',
    aprovarMicro: 'A partir daqui o Forge escreve na pasta e executa os comandos. Revise o plano acima antes.',
    titulo: 'Materialização',
    estado: {
      escrevendo: 'Escrevendo os arquivos…',
      rodando: 'Executando os comandos…',
      parado_em_falha: 'Um comando falhou. Você decide o que fazer.',
      concluida: 'Pronto. O projeto nasceu.',
      abortada: 'Materialização abortada. O que já foi escrito continua no disco.',
    },
    arquivos: (criados, sobrescritos, pulados) => `${criados} criados, ${sobrescritos} sobrescritos, ${pulados} pulados.`,
    comandoEstado: {
      pendente: 'na fila',
      rodando: 'rodando',
      sucesso: 'ok',
      falha: 'falhou',
      timeout: 'tempo esgotado',
      cancelado: 'parado',
      pulado: 'pulado',
    },
    repetir: 'Repetir',
    pular: 'Pular este comando',
    abortar: 'Abortar',
    parar: 'Parar',
    ferramentasAusentes: 'Falta instalar antes de materializar:',
    ferramentaLinha: (bin, min, encontrada) => (encontrada ? `${bin}: encontrei ${encontrada}, preciso de ${min} ou maior` : `${bin}: não encontrei nesta máquina`),
    planoVelho: 'O blueprint mudou depois deste plano. Recarregue para gerar um plano novo.',
    saidaDe: (id) => `Saída de ${id}`,
  },
  regras: {
    severidade: { info: 'dica', aviso: 'aviso', bloqueio: 'bloqueio' },
    automatico: 'O plano já cuida disso. Nada a fazer.',
    dispensar: 'Dispensar',
    reabrir: 'Reabrir',
    ignorar: 'Ignorar',
    cancelar: 'Cancelar',
    confirmarDispensa: 'Confirmar dispensa',
    dispensado: 'Dispensado',
    ignorado: 'Ignorado',
    resolvido: 'Resolvido',
    justificativa: {
      rotulo: 'Por que este aviso não se aplica aqui',
      micro: 'Fica registrado no projeto, junto com a data. Mínimo de 10 caracteres.',
      curta: 'Escreva ao menos 10 caracteres.',
    },
    bloqueioMaterializar: 'Resolva os bloqueios abertos antes de chegar em Materializar.',
    bloqueiosAbertos: (n) => (n === 1 ? '1 bloqueio aberto' : `${n} bloqueios abertos`),
    semBloqueios: 'Nenhum bloqueio aberto.',
    resolverBloqueios: 'Ver os bloqueios',
  },
  lista: {
    adicionar: 'Adicionar',
    remover: 'Remover',
    vazio: 'Nada aqui ainda. Escreva abaixo e adicione.',
    novoItem: (rotulo) => `Novo item de ${rotulo}`,
  },
  wizard: {
    trilha: 'Etapas do projeto',
    avisos: 'Avisos do motor de regras',
    voltar: 'Voltar',
    avancar: 'Avançar',
    pular: 'Pular etapa',
    concluir: 'Concluir',
    etapaXdeY: (x, y) => `Etapa ${x} de ${y}`,
    notaSalvamento: 'O blueprint é salvo a cada avanço, e só quando algo muda. Sair sem avançar perde o que está na tela.',
    erroSalvar: 'Não deu para salvar o blueprint.',
    arquivado: {
      titulo: 'Projeto arquivado',
      texto: 'Restaure o projeto para voltar a editar o blueprint.',
    },
    estado: {
      atual: 'agora',
      concluida: 'ok',
      assumida: 'assumida',
      visitada: 'aberta',
      pendente: 'a fazer',
    },
    sim: 'Sim',
    nao: 'Não',
    passos: {
      identidade: {
        titulo: 'O que é este projeto',
        micro: 'Estas respostas viram memory/identity.md, docs/00_VISAO e o README do projeto gerado.',
        nome: { rotulo: 'Nome do projeto', micro: 'Renomeia o projeto. O slug da pasta não muda.' },
        essencia: { rotulo: 'Essência em uma frase', micro: 'Abre o README e o docs/00_VISAO.', placeholder: 'Uma bancada local que transforma método em software.' },
        problema: { rotulo: 'Problema que resolve', micro: 'Vira a seção "O problema" em docs/00_VISAO.', placeholder: 'Começar um projeto novo custa caro em tempo e memória.' },
        valor: { rotulo: 'Proposta de valor', micro: 'Vira o propósito central em memory/identity.md.', placeholder: 'O caminho vira trilho, não depende mais de lembrar.' },
        nomeVazio: 'O projeto precisa de um nome.',
      },
      escopo: {
        titulo: 'Para quem, e até onde',
        micro: 'Vira as personas e os não-objetivos em memory/identity.md.',
        publico: { rotulo: 'Público-alvo', micro: 'Quem usa isso no dia a dia.', placeholder: 'Uso pessoal, depois qualquer dev da Kora.' },
        personas: { rotulo: 'Personas', micro: 'Uma linha por pessoa, com a dor real dela.', placeholder: 'Matheus, toca várias frentes ao mesmo tempo' },
        ahaMoment: { rotulo: 'Aha moment', micro: 'O instante em que a pessoa entende o valor.', placeholder: 'Ver a pasta nascer no disco com tudo preenchido.' },
        naoObjetivos: { rotulo: 'Não-objetivos', micro: 'O que este produto nunca será. Corta escopo antes de custar código.', placeholder: 'Não é IDE' },
      },
      arquitetura: {
        titulo: 'Como isso vai ser construído',
        micro: 'Vira docs/01_ARQUITETURA e o ADR-001 do projeto gerado. Tudo já vem com o padrão do menu escolhido.',
        modelo: { rotulo: 'Modelo de arquitetura', micro: 'A: SPA com backend como serviço. B: SPA com API própria. C: serviço sem interface.' },
        modelos: { A: 'Modelo A, SPA mais BaaS', B: 'Modelo B, SPA mais API própria', C: 'Modelo C, serviço sem interface' },
        stack: { rotulo: 'Stack', micro: 'Entra no CLAUDE.md e no package.json do projeto gerado.', placeholder: 'supabase' },
        multiTenant: { rotulo: 'Multi-tenant', micro: 'Padrão Kora: toda tabela nasce com tenant_id e RLS.' },
        whiteLabel: { rotulo: 'White-label', micro: 'Marca e cores vêm do tenant, nunca hardcodadas.' },
        auth: { rotulo: 'Tem login', micro: 'Liga guarda de rota e estado de sessão no projeto gerado.' },
        deploy: { rotulo: 'Deploy', micro: 'Onde isso roda em produção. "nenhum" para ferramenta local.', placeholder: 'vercel' },
      },
      dados: {
        titulo: 'O que este sistema guarda',
        micro: 'Vira docs/04_MODELAGEM e o schema.sql do projeto gerado.',
        entidades: { rotulo: 'Entidades', micro: 'Uma por coisa que o sistema guarda. Ex.: pedido, cliente, produto.' },
        vazio: 'Nenhuma entidade ainda. Comece pela principal, aquela sem a qual o produto não existe.',
        adicionar: 'Adicionar entidade',
        remover: 'Remover entidade',
        nome: { rotulo: 'Nome', placeholder: 'pedido' },
        descricao: { rotulo: 'O que é', placeholder: 'Um pedido feito por um cliente.' },
        campos: { rotulo: 'Campos', micro: 'Um por linha. tenant_id e timestamps são adicionados pelo padrão.', placeholder: 'valor_total' },
      },
      seguranca: {
        titulo: 'Segurança e custo',
        micro: 'Vira docs/11_SEGURANCA e as restrições de custo em memory/restrictions.md.',
        dadoPessoal: { rotulo: 'Trata dado pessoal', micro: 'Liga a seção de LGPD, base legal e retenção.' },
        dadoFinanceiro: { rotulo: 'Trata dinheiro', micro: 'Exige lógica sensível no servidor, nunca no cliente.' },
        compliance: { rotulo: 'Exigências de compliance', micro: 'Norma ou lei que incide. Vazio quando não há.', placeholder: 'LGPD' },
        tierGratuito: { rotulo: 'Tudo em tier gratuito', micro: 'Fase bootstrap: serviço pago entra só por decisão explícita.' },
        observacoes: { rotulo: 'Observações', micro: 'O que mais precisa entrar no plano de segurança.' },
      },
      fundacao: {
        titulo: 'Revisão da fundação',
        micro: 'Isto é o que a materialização vai escrever. Nada é criado ainda.',
        gerado: 'O que será gerado',
        assumidas: 'Etapas assumidas com o padrão do menu',
        pendentes: 'Etapas ainda sem resposta',
        nenhumaAssumida: 'Nenhuma. Você respondeu tudo.',
        nenhumaPendente: 'Nenhuma.',
        observacoes: { rotulo: 'Observações', micro: 'Vira uma nota em docs/09_BACKLOG do projeto gerado.' },
      },
      materializar: {
        titulo: 'Materializar',
        micro: 'A última etapa. Aqui o Forge mostra o plano de arquivos e comandos antes de tocar no disco.',
        confirmada: { rotulo: 'Revisei o blueprint', micro: 'Marca o blueprint como revisado. Nada é escrito em disco por isso.' },
      },
      futura: {
        design: { titulo: 'Design', micro: 'O Studio, editor visual do design system do projeto, chega na Fase 2.', texto: 'Por enquanto o projeto gerado sai com o tema padrão do menu. Continuar marca esta etapa como assumida.' },
        apis: { titulo: 'APIs e integrações', micro: 'O API Hub e o cofre de segredos chegam na Fase 3.', texto: 'Por enquanto nenhuma chave é conectada. Continuar marca esta etapa como assumida.' },
        continuar: 'Continuar',
      },
    },
  },
};
