// Todo texto de UI vive aqui. Interface em português, sem i18n na Fase 1, mas com as strings
// já extraídas para não pagar refatoração depois (memory/decisions.md).
export const mensagens = {
  app: {
    nome: 'KORA FORGE',
    navegacao: 'Navegação principal',
    semProjetoAtivo: 'Nenhum projeto ativo',
    versaoDesconhecida: '…',
  },
  menu: {
    projetos: 'Projetos',
    config: 'Configurações',
  },
  estados: {
    carregando: 'Carregando…',
    erroGenerico: 'Não deu para falar com a API local.',
    tentarDeNovo: 'Tentar de novo',
  },
  semSessao: {
    titulo: 'Abra o Forge pelo link do terminal',
    texto: 'O link impresso pelo comando abaixo carrega o token de sessão. Sem ele, o browser não consegue falar com a API local, de propósito.',
    comando: 'npm run forge',
    comandoRotulo: 'comando para subir o Forge',
  },
  registry: {
    titulo: 'Projetos',
    novo: 'Novo projeto',
    busca: { rotulo: 'Buscar', micro: 'Filtra por nome ou slug.', placeholder: 'nome ou slug' },
    filtro: {
      rotulo: 'Status',
      micro: 'Arquivados só aparecem escolhendo o filtro.',
      ativos: 'Ativos',
      rascunho: 'Rascunho',
      pronto_para_materializar: 'Pronto para materializar',
      materializado: 'Materializado',
      arquivado: 'Arquivados',
    },
    vazio: {
      titulo: 'Nenhum projeto ainda',
      texto: 'Escolha um menu para começar. O wizard preenche o blueprint e a materialização cria a pasta.',
    },
    semResultado: {
      titulo: 'Nenhum projeto com esse filtro',
      texto: 'Tente outro nome ou outro status.',
      limpar: 'Limpar filtros',
    },
    avisoWorkspace: 'Nenhum workspace configurado. Dá para criar projetos, mas materializar exige a pasta raiz.',
    configurar: 'Configurar workspace',
    ultimaAlteracao: 'Alterado em',
    etapa: 'Etapa',
    semCaminho: 'ainda não materializado',
  },
  preset: {
    etapasSufixo: 'etapas',
    categoria: { site: 'Site', aplicacao: 'Aplicação', api: 'API', automacao: 'Automação' },
  },
  novoProjeto: {
    titulo: 'Novo projeto',
    escolha: 'Escolha o menu',
    escolhido: 'Menu escolhido',
    trocar: 'Trocar menu',
    nome: {
      rotulo: 'Nome do projeto',
      micro: 'Vira o nome da pasta e o slug do repositório.',
      slug: 'Slug',
      slugVazio: 'digite um nome com letra ou número',
      placeholder: 'Meu app',
    },
    criar: 'Criar projeto',
    voltar: 'Voltar para projetos',
  },
  projeto: {
    naoEncontrado: 'Projeto não encontrado.',
    voltar: 'Voltar para projetos',
    preset: 'Menu',
    etapaAtual: 'Próxima etapa',
    caminho: 'Pasta',
    semCaminho: 'ainda não materializado',
    renomear: 'Renomear',
    salvarNome: 'Salvar nome',
    cancelar: 'Cancelar',
    nome: { rotulo: 'Nome', micro: 'O slug não muda ao renomear.' },
    arquivar: 'Arquivar',
    restaurar: 'Restaurar',
    arquivado: 'Projeto arquivado. Restaure para continuar.',
    wizardIndisponivel: 'O wizard ainda não está disponível. O blueprint fica na etapa inicial até lá.',
    versoes: 'Versões do blueprint',
    versaoAtiva: 'ativa',
    blueprintVersao: 'Blueprint',
  },
  etapas: {
    identidade: 'Identidade',
    escopo: 'Escopo e público',
    arquitetura: 'Arquitetura e stack',
    design: 'Design',
    dados: 'Dados e entidades',
    apis: 'APIs e integrações',
    seguranca: 'Segurança e custo',
    fundacao: 'Fundação',
    materializar: 'Materializar',
  },
  config: {
    titulo: 'Configurações',
    salvar: 'Salvar',
    salvo: 'Configurações salvas.',
    workspace: {
      rotulo: 'Workspace',
      micro: 'Pasta raiz onde os projetos são criados. Nada é escrito fora dela.',
      placeholder: 'D:\\dev\\kora',
    },
    tema: {
      rotulo: 'Tema',
      micro: 'Aparência da ferramenta. O tema claro chega na Fase 5.',
      escuro: 'Escuro',
      claro: 'Claro',
    },
    teto: {
      rotulo: 'Teto mensal do copiloto (USD)',
      micro: 'Quando o consumo bate o teto, o copiloto desliga sozinho.',
      invalido: 'Informe um número maior ou igual a zero.',
    },
  },
  campo: {
    padrao: 'Padrão',
  },
  selecao: {
    padraoKora: 'padrão Kora',
  },
  selo: {
    rascunho: 'rascunho',
    pronto: 'pronto',
    materializado: 'materializado',
    arquivado: 'arquivado',
    ativa: 'ativa',
    invalida: 'inválida',
  },
  chave: {
    copiar: 'Copiar',
    copiado: 'Copiado',
  },
};
