// Textos da página Auto-Reforja (T09). Dono exclusivo: a frente da Auto-Reforja.
export const mensagensReforja = {
  titulo: 'Auto-Reforja',
  subtitulo: 'O lugar onde o Forge melhora a própria forja: veja o que o diagnóstico encontrou, transforme em melhoria e leve cada uma pelo ciclo spec, build e review.',

  severidades: { alta: 'Alta', media: 'Média', baixa: 'Baixa' },
  unidades: { ocorrencias: 'ocorrências', linhas: 'linhas', criterios: 'critérios', blocos: 'blocos', arquivos: 'arquivos' },
  prioridades: { alta: 'Alta', media: 'Média', baixa: 'Baixa' },
  origens: { manual: 'Criada por você', diagnostico: 'Do diagnóstico', modelo: 'Sugerida por modelo' },

  diagnostico: {
    titulo: 'Diagnóstico do Forge',
    descricao: 'Leitura só de consulta do código, das specs e do backlog do próprio Forge. Nada é escrito.',
    atualizar: 'Diagnosticar de novo',
    resumo: (total, arquivos) => `${total} ${total === 1 ? 'sinal' : 'sinais'} em ${arquivos} arquivos lidos.`,
    vazioTitulo: 'Nenhum sinal encontrado.',
    vazioAcao: 'A forja está em dia. Rode o diagnóstico de novo depois da próxima entrega.',
    arquivos: (total) => `${total} ${total === 1 ? 'arquivo' : 'arquivos'}`,
    evidencias: 'Onde aparece',
    evidenciasOcultas: (quantas) => `e mais ${quantas} ${quantas === 1 ? 'arquivo' : 'arquivos'}`,
    transformar: 'Transformar em melhoria',
    jaNoBacklog: 'Já está no backlog',
    transformado: (titulo) => `Melhoria criada: ${titulo}.`,
    jaExistia: (titulo) => `Esse sinal já estava no backlog: ${titulo}.`,
  },

  backlog: {
    titulo: 'Backlog de melhorias',
    descricao: 'Cada melhoria anda pelo ciclo do harness. O Forge guarda em que ponto ela está e diz o próximo passo.',
    vazioTitulo: 'O backlog está vazio.',
    vazioAcao: 'Transforme um sinal do diagnóstico em melhoria, ou crie uma abaixo.',
    colunaVazia: 'Nada aqui.',
    descartadas: (total) => `Descartadas (${total})`,
    descartadasVazio: 'Nenhuma melhoria descartada.',
    estados: {
      proposta: 'Proposta',
      especificada: 'Especificada',
      em_construcao: 'Em construção',
      em_revisao: 'Em revisão',
      concluida: 'Concluída',
      descartada: 'Descartada',
    },
    depois: {
      proposta: 'Gere a spec pela prévia, ou escreva a spec e avance.',
      especificada: 'Rode /build com a spec e avance para em construção.',
      em_construcao: 'Quando o build terminar, avance para revisão e rode /review.',
      em_revisao: 'Com a auditoria toda em sim, conclua. Se achou problema, volte para construção.',
      concluida: 'Pronto. Reabra a revisão se aparecer regressão.',
      descartada: 'Fica guardada e pode ser restaurada como proposta.',
    },
    acoes: {
      avancar: (para) => `Avançar para ${para}`,
      voltar: (para) => `Voltar para ${para}`,
      descartar: 'Descartar',
      restaurar: 'Restaurar como proposta',
      gerarSpec: 'Gerar spec',
    },
    confirmarDescarte: 'Descartar esta melhoria? Ela fica guardada e pode ser restaurada.',
    confirmarDescarteSim: 'Sim, descartar',
    confirmarDescarteNao: 'Manter',
    specEm: 'Spec:',
    estadoMudou: (titulo, para) => `${titulo} agora está em ${para}.`,
  },

  novo: {
    titulo: 'Nova melhoria',
    campoTitulo: 'Título',
    campoTituloMicro: 'Uma frase que diga o que melhora. Vira o nome da spec.',
    campoDescricao: 'Descrição',
    campoDescricaoMicro: 'Opcional. Contexto e o porquê, entra no escopo da spec.',
    campoPrioridade: 'Prioridade',
    campoPrioridadeMicro: 'Define a ordem no backlog: alta aparece primeiro.',
    tituloObrigatorio: 'Escreva um título para a melhoria.',
    criar: 'Criar melhoria',
    criada: (titulo) => `Melhoria criada: ${titulo}. Ela entrou como proposta.`,
  },

  spec: {
    titulo: 'Prévia da spec',
    tituloDe: (titulo) => `Prévia da spec: ${titulo}`,
    descricao: 'Nada foi gravado ainda. Confira o caminho e o conteúdo antes de confirmar.',
    caminho: 'Vai ser gravada em',
    versao: (versao) => `Template versão ${versao}`,
    carregando: 'Montando a prévia…',
    existe: 'Já existe um arquivo nesse caminho. Gravar vai substituir o conteúdo dele.',
    sobrescrever: 'Substituir o arquivo existente',
    confirmar: 'Gravar spec',
    cancelar: 'Fechar prévia',
    gravada: (caminho) => `Spec gravada em ${caminho}. Próximo passo: rode /build com ela.`,
  },

  sugestoes: {
    titulo: 'Sugestões de um modelo gratuito',
    descricao: 'Opcional. Um modelo gratuito lê só o resumo do diagnóstico e propõe melhorias. Nada entra no backlog sem o seu clique.',
    pedir: 'Pedir sugestões',
    pedindo: 'Pedindo sugestões…',
    indisponivel: {
      sem_modelos: 'O gateway de modelos gratuitos não está configurado neste Forge.',
      desligado: 'Os modelos gratuitos estão desligados.',
      desconectado: 'O gateway de modelos gratuitos não respondeu.',
    },
    irConfiguracoes: 'Abrir Configurações',
    semPropostas: 'O modelo não trouxe nenhuma proposta aproveitável. Tente de novo mais tarde.',
    formatoNaoReconhecido: 'A resposta veio num formato que o Forge não entende, então nada foi aproveitado.',
    descartadas: (quantas) => `${quantas} ${quantas === 1 ? 'proposta foi ignorada' : 'propostas foram ignoradas'} por passar do limite ou repetir título.`,
    doModelo: (modelo) => `Respondido por ${modelo}.`,
    aceitar: 'Aceitar',
    dispensar: 'Dispensar',
    aceita: (titulo) => `Proposta aceita: ${titulo}. Ela entrou no backlog como proposta.`,
    todasResolvidas: 'Todas as propostas foram resolvidas.',
  },
};
